dependency-updates
osisoft/sample-adh-grafana-nodejs pull request #25
Opened 2022-01-11 00:22 UTC by cbardini

2022-01-11 13:42 UTC, derekendres approved these changes

2022-01-11 22:21 UTC, kelseyduffy approved these changes

2022-01-24 18:20 UTC, cbardini commented
/azp run

2022-03-15 20:26 UTC, anton-dahlin requested changes

2022-03-15 20:26 UTC, anton-dahlin commented on HISTORY.md
> +## 1.2.10 / 2022-01-17
fix date

2022-03-16 14:37 UTC, kelseyduffy requested changes
this PR never got merged, and I'd recommend closing it out. The dependency update PR behind this one can supersede it with more up to date dependency versions, as well as the ADH change

2022-03-29 14:30 UTC, closed without merging